# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ThermoStateCalc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGroupBox, QVBoxLayout, QHBoxLayout, QLabel


from PyQt5.QtWidgets import QGroupBox, QVBoxLayout, QHBoxLayout, QLabel

class Ui__frm_StateCalculator(object):
    def setupUi(self, _frm_StateCalculator):
        _frm_StateCalculator.setObjectName("_frm_StateCalculator")
        _frm_StateCalculator.resize(528, 516)
        self.verticalLayout = QtWidgets.QVBoxLayout(_frm_StateCalculator)
        self.verticalLayout.setObjectName("verticalLayout")
        self._grp_Units = QtWidgets.QGroupBox(_frm_StateCalculator)
        self._grp_Units.setObjectName("_grp_Units")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self._grp_Units)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self._rdo_SI = QtWidgets.QRadioButton(self._grp_Units)
        self._rdo_SI.setChecked(True)
        self._rdo_SI.setObjectName("_rdo_SI")
        self.horizontalLayout_2.addWidget(self._rdo_SI)
        self._rdo_English = QtWidgets.QRadioButton(self._grp_Units)
        self._rdo_English.setObjectName("_rdo_English")
        self.horizontalLayout_2.addWidget(self._rdo_English)
        self.verticalLayout.addWidget(self._grp_Units)
        self._grp_SpecifiedProperties = QtWidgets.QGroupBox(_frm_StateCalculator)
        self._grp_SpecifiedProperties.setObjectName("_grp_SpecifiedProperties")
        self.gridLayout = QtWidgets.QGridLayout(self._grp_SpecifiedProperties)
        self.gridLayout.setObjectName("gridLayout")
        self._le_Property1 = QtWidgets.QLineEdit(self._grp_SpecifiedProperties)
        self._le_Property1.setObjectName("_le_Property1")
        self.gridLayout.addWidget(self._le_Property1, 2, 0, 1, 1)
        self._le_Property2 = QtWidgets.QLineEdit(self._grp_SpecifiedProperties)
        self._le_Property2.setObjectName("_le_Property2")
        self.gridLayout.addWidget(self._le_Property2, 2, 3, 1, 1)
        self._lbl_Property1_Units = QtWidgets.QLabel(self._grp_SpecifiedProperties)
        self._lbl_Property1_Units.setObjectName("_lbl_Property1_Units")
        self.gridLayout.addWidget(self._lbl_Property1_Units, 2, 1, 1, 1)
        self._cmb_Property1 = QtWidgets.QComboBox(self._grp_SpecifiedProperties)
        self._cmb_Property1.setObjectName("_cmb_Property1")
        self._cmb_Property1.addItem("")
        self._cmb_Property1.addItem("")
        self._cmb_Property1.addItem("")
        self._cmb_Property1.addItem("")
        self._cmb_Property1.addItem("")
        self._cmb_Property1.addItem("")
        self._cmb_Property1.addItem("")
        self.gridLayout.addWidget(self._cmb_Property1, 1, 0, 1, 2)
        self._lbl_Property2_Units = QtWidgets.QLabel(self._grp_SpecifiedProperties)
        self._lbl_Property2_Units.setObjectName("_lbl_Property2_Units")
        self.gridLayout.addWidget(self._lbl_Property2_Units, 2, 4, 1, 1)
        self._lbl_Property1 = QtWidgets.QLabel(self._grp_SpecifiedProperties)
        self._lbl_Property1.setObjectName("_lbl_Property1")
        self.gridLayout.addWidget(self._lbl_Property1, 0, 0, 1, 1)
        self._lbl_Property2 = QtWidgets.QLabel(self._grp_SpecifiedProperties)
        self._lbl_Property2.setObjectName("_lbl_Property2")
        self.gridLayout.addWidget(self._lbl_Property2, 0, 3, 1, 1)
        self._lbl_Warning = QtWidgets.QLabel(self._grp_SpecifiedProperties)
        self._lbl_Warning.setText("")
        self._lbl_Warning.setObjectName("_lbl_Warning")
        self.gridLayout.addWidget(self._lbl_Warning, 3, 0, 1, 5)
        self._cmb_Property2 = QtWidgets.QComboBox(self._grp_SpecifiedProperties)
        self._cmb_Property2.setObjectName("_cmb_Property2")
        self._cmb_Property2.addItem("")
        self._cmb_Property2.addItem("")
        # Add more items as needed
        self.gridLayout.addWidget(self._cmb_Property2, 1, 3, 1, 2)
        self.verticalLayout.addWidget(self._grp_SpecifiedProperties)

        # Group box for State Properties
        self._grp_StateProperties = QtWidgets.QGroupBox(_frm_StateCalculator)
        self._grp_StateProperties.setObjectName("_grp_StateProperties")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self._grp_StateProperties)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # Group box for State 1
        self.state1_groupbox = QGroupBox("State 1")
        state1_layout = QHBoxLayout()
        state1_layout.addWidget(QLabel("State 1:"))
        state1_layout.addWidget(QLabel("100 kPa"))  # Placeholder value, replace with actual value
        state1_layout.addWidget(QLabel("50°C"))  # Placeholder value, replace with actual value
        self.state1_groupbox.setLayout(state1_layout)
        self.verticalLayout_2.addWidget(self.state1_groupbox)

        # Group box for State 2
        self.state2_groupbox = QGroupBox("State 2")
        state2_layout = QHBoxLayout()
        state2_layout.addWidget(QLabel("State 2:"))
        state2_layout.addWidget(QLabel("200 kPa"))  # Placeholder value, replace with actual value
        state2_layout.addWidget(QLabel("100°C"))  # Placeholder value, replace with actual value
        self.state2_groupbox.setLayout(state2_layout)
        self.verticalLayout_2.addWidget(self.state2_groupbox)

        # Group box for State Change
        self.state_change_groupbox = QGroupBox("State Change")
        state_change_layout = QHBoxLayout()
        state_change_layout.addWidget(QLabel("State Change:"))
        state_change_layout.addWidget(QLabel("100 kPa"))  # Placeholder value, replace with actual value
        state_change_layout.addWidget(QLabel("50°C"))  # Placeholder value, replace with actual value
        self.state_change_groupbox.setLayout(state_change_layout)
        self.verticalLayout_2.addWidget(self.state_change_groupbox)

        self.verticalLayout.addWidget(self._grp_StateProperties)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(_frm_StateCalculator)
        self._cmb_Property2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(_frm_StateCalculator)

    def retranslateUi(self, _frm_StateCalculator):
        _translate = QtCore.QCoreApplication.translate
        _frm_StateCalculator.setWindowTitle(_translate("_frm_StateCalculator", "Thermodynamic State Calculator"))
        self._grp_Units.setTitle(_translate("_frm_StateCalculator", "System of Units"))
        self._rdo_SI.setText(_translate("_frm_StateCalculator", "SI"))
        self._rdo_English.setText(_translate("_frm_StateCalculator", "English"))
        self._grp_SpecifiedProperties.setTitle(_translate("_frm_StateCalculator", "Specified Properties"))
        self._le_Property1.setText(_translate("_frm_StateCalculator", "1.0"))
        self._le_Property2.setText(_translate("_frm_StateCalculator", "100.0"))
        self._lbl_Property1_Units.setText(_translate("_frm_StateCalculator", "Bar"))
        self._cmb_Property1.setItemText(0, _translate("_frm_StateCalculator", "Pressure (p)"))
        self._cmb_Property1.setItemText(1, _translate("_frm_StateCalculator", "Temperature (T)"))
        self._cmb_Property1.setItemText(2, _translate("_frm_StateCalculator", "Quality (x)"))
        self._cmb_Property1.setItemText(3, _translate("_frm_StateCalculator", "Specific Internal Energy (u)"))
        self._cmb_Property1.setItemText(4, _translate("_frm_StateCalculator", "Specific Enthalpy (h)"))
        self._cmb_Property1.setItemText(5, _translate("_frm_StateCalculator", "Specific Volume (v)"))
        self._cmb_Property1.setItemText(6, _translate("_frm_StateCalculator", "Specific Entropy (s)"))
        self._lbl_Property2_Units.setText(_translate("_frm_StateCalculator", "C"))
        self._lbl_Property1.setText(_translate("_frm_StateCalculator", "Property 1"))
        self._lbl_Property2.setText(_translate("_frm_StateCalculator", "Property 2"))
        self._cmb_Property2.setItemText(0, _translate("_frm_StateCalculator", "Pressure (p)"))
        self._cmb_Property2.setItemText(1, _translate("_frm_StateCalculator", "Temperature (T)"))
        self._cmb_Property2.setItemText(2, _translate("_frm_StateCalculator", "Quality (x)"))
        self._cmb_Property2.setItemText(3, _translate("_frm_StateCalculator", "Specific Internal Energy (u)"))
        self._cmb_Property2.setItemText(4, _translate("_frm_StateCalculator", "Specific Enthalpy (h)"))
        self._cmb_Property2.setItemText(5, _translate("_frm_StateCalculator", "Specific Volume (v)"))
        self._cmb_Property2.setItemText(6, _translate("_frm_StateCalculator", "Specific Entropy (s)"))
        self._pb_Calculate.setText(_translate("_frm_StateCalculator", "Calculate"))
        self._grp_StateProperties.setTitle(_translate("_frm_StateCalculator", "State Properties"))
        self._lbl_State.setText(_translate("_frm_StateCalculator", "State:  saturated"))
        self._lbl_StateProperties.setText(_translate("_frm_StateCalculator", "Pressure = 1000 kPa\n"
                                                                             "Temperature = 100 C\n"
                                                                             "X = 1.0"))
